---
# current regression test suite do not support ipv6, so we have to disable
# it
- lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
    regexp: ^IPV6INIT=
    line: IPV6INIT=no
  name: "Disable ipv6 in ifcfg"

- lineinfile:
    dest: /etc/sysconfig/network
    regexp: ^NETWORKING_IPV6=
    line: NETWORKING_IPV6=no
  name: Disable ipv6 in network config

# force the hostonly option, since ec2 has a package installed
# that disable it, who break rpcbind, which break test suite
# see https://lists.gluster.org/pipermail/gluster-infra/2019-April/005519.html
- copy:
    dest: /etc/dracut.conf.d/disable_ipv6.conf
    content: 'hostonly="yes"'

- sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  with_items:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6
  name: Disable ipv6 in sysctl
  register: sysctl
 
- name: Run dracut
  command:  dracut -v -f -H
  when: sysctl.changed

# use "install ipv6 /bin/true", since that's what ip6tables check to see if
# ipv6 is disabled. See reload function on /etc/init.d/ip6tables on RHEL 6.
- copy:
    dest: /etc/modprobe.d/ipv6.conf
    content: "options ipv6 disable=1\ninstall ipv6 /bin/true"
  name: Disable ipv6 module
