---
- name: Create systemd tmpfile
  shell: systemd-tmpfiles --create /etc/tmpfiles.d/softserve.conf

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Restart softserve backend
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
   with_items:
     - softserve
     - softserve-celery
