---
- src: https://github.com/OSAS/ansible-role-ansible_bastion
  name: bastion
- src: git+https://gitlab.com/OSAS/ansible-role-tor.git
  name: tor
- src: git+https://gitlab.com/OSAS/ansible-role-shell_timeout.git
  name: shell_timeout
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd
- src: https://github.com/OSAS/ansible-role-openssh
  name: openssh
- src: git+https://gitlab.com/osci/ansible-role-selinux.git
  name: selinux
- src: https://github.com/OSAS/ansible-role-web_builder
  name: builder
- src: git+https://gitlab.com/osas/ansible-role-ntp.git
  name: ntp
- src: git+https://gitlab.com/osas/ansible-role-libvirt.git
  name: libvirt
- src: git+https://gitlab.com/osas/ansible-role-munin.git
  name: munin
- src: git+https://gitlab.com/osas/ansible-role-lvm_config.git
  name: lvm_config
- src: git+https://gitlab.com/osas/ansible-role-memcached.git
  name: memcached
- src: git+https://gitlab.com/osas/ansible-role-pf_firewall.git
  name: pf_firewall
- src: git+https://gitlab.com/osas/ansible-role-unattended_updates.git
  name: unattended_updates
- src: git+https://gitlab.com/osas/ansible-role-postgrey.git
  name: postgrey
- src: git+https://gitlab.com/misc/ansible-role-guest_virt_install.git
  name: guest_virt_install
  version: fix_el7
- src: git+https://gitlab.com/osas/ansible-role-xinetd.git
  name: xinetd
- src: git+https://gitlab.com/misc/ansible-role-postgresql.git
  name: postgresql
  version: open_network
- src: https://github.com/OSAS/ansible-role-mariadb
  name: mariadb
- src: https://github.com/OSAS/ansible-role-swap_file
  name: swap_file
- src: https://github.com/OSAS/ansible-role-polyinst_tmp
  name: polyinst_tmp
- src: git+https://gitlab.com/osas/ansible-role-redis.git
  name: redis
- src: git+https://gitlab.com/osas/ansible-role-entropy.git
  name: entropy
- src: git+https://gitlab.com/osas/ansible-role-sasldb.git
  name: sasldb
- src: git+https://gitlab.com/osas/ansible-role-chrony.git
  name: chrony
- src: git+https://gitlab.com/osci/ansible-role-aws-s3_bucket_backup.git
  name: aws-s3_bucket_backup
