---
- shell: ssh-keygen -q -P '' -C "key for georep test" -f /root/.ssh/id_georep
  name: Generate a key for georep
  args:
    creates: /root/.ssh/id_georep

- shell: cat /root/.ssh/id_georep.pub
  name: Get the public key
  register: georep_pub_key
  changed_when: False

- name: Link the key to the default key
  file:
    state: link
    src: /root/.ssh/id_georep{{ item }}
    dest: /root/.ssh/id_rsa{{ item }}
  with_items:
  - ''
  - '.pub'
 
- authorized_key:
    user: root
    key: "{{ georep_pub_key.stdout }}"
    key_options: ''
  name: Add authorized_key for georep tests

# see https://bugzilla.redhat.com/show_bug.cgi?id=1532591
- name: Add glusterfs to $PATH for georep
  copy:
    content: "export PATH=$PATH:/build/install/sbin:/build/install/bin"
    dest: /etc/profile.d/georep.sh
  when: ansible_system == 'Linux'
