---
- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder standard packages
  with_items:
  - git
  - dbench
  - yajl
  - sudo
  - gcc  

- package:
    state: present
    name: centos-release-scl
  name: Enable SCL
  when: '"jenkins_builders_rht" in group_names and ansible_distribution == "CentOS"'

- package:
    state: present
    name: "{{item}}"
  name: Add packages specific to rht builders
  with_items:
  - python27
  - python-libcloud
  - cppcheck
  - clang
  - clang-analyzer
  - lcov  
  when: '"jenkins_builders_rht" in group_names and ansible_distribution == "CentOS"'

- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder Linux packages
  when: ansible_system == 'Linux'
  with_items:
  # needed for some tests
  - net-tools
  # used for smoke.sh, for killall
  - psmisc
  - libacl-devel
  - nfs-utils
  - automake
  - autoconf
  - libtool
  - flex
  - bison
  - cmockery2-devel
  - perl-Test-Harness
  - openssl-devel
  - lvm2-devel
  - sqlite-devel
  - libxml2-devel
  - python-devel
  - userspace-rcu-devel
  - libibverbs-devel
  - librdmacm-devel
  - libaio-devel
  - clang-analyzer
  # needed to make rpm
  - rpm-build
  - xfsprogs
# used for testing eventing
  - python-requests
  - python-flask
  - python-prettytable
# used for build-jobs testing
  - python-virtualenv
  - python-argparse
# used for utils/create-files.py
  - pyxattr
# used for cli
  - ncurses-devel
  - readline-devel
# tmpwatch to clean /tmp
  - tmpwatch

- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder FreeBSD packages
  when: ansible_system == 'FreeBSD'
  with_items:
  - cmockery2
  - perl5
  - openjdk8-jre
  - sqlite3

- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder jdk for RHEL/Centos/Fedora
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'
  with_items:
  - java-1.8.0-openjdk

- package:
    state: absent
    name: "{{ item }}"
  name: Remove package that cause trouble with the regression suite
  with_items:
  - qemu-img
