---
- package: state=present name={{ item }}
  name: Install jenkins builder standard packages
  with_items:
  - git
  - dbench
  - yajl

- package: state=present name={{ item }}
  name: Install jenkins builder Linux packages
  when: ansible_system == 'Linux'
  with_items:
  # needed for some tests
  - net-tools
  # used for smoke.sh, for killall
  - psmisc
  - libacl-devel
  - nfs-utils
  - automake
  - autoconf
  - libtool
  - flex
  - bison
  - cmockery2-devel
  - perl-Test-Harness
  - openssl-devel
  - lvm2-devel
  - sqlite-devel
  - libxml2-devel
  - python-devel
  - userspace-rcu-devel
  - libibverbs-devel
  - librdmacm-devel
  - libaio-devel
  - clang-analyzer
  # needed to make rpm
  - rpm-build
  # needed for REST APIs and Eventing
  - golang
  - golang-github-gorilla-mux-devel
# still in testing, https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-8108
#  - golang-github-gorilla-handlers-devel
  - golang-github-gorilla-websocket-devel
  - golang-github-dgrijalva-jwt-go-devel
  - golang-github-Sirupsen-logrus-devel
  - xfsprogs
# used for testing eventing
  - python-requests
  - python-flask
  - python-prettytable
# used for build-jobs testing
  - python-virtualenv
  - python-argparse

- package: state=present name={{ item }}
  name: Install jenkins builder FreeBSD packages
  when: ansible_system == 'FreeBSD'
  with_items:
  - cmockery2
  - perl5
  - openjdk8-jre
  - sqlite3

- package: state=present name={{ item }}
  name: Install jenkins builder jdk for RHEL/Centos
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
  with_items:
  - java-1.7.0-openjdk

- package: state=present name={{ item }}
  name: Install jenkins builder jdk for RHEL/Centos
  when: ansible_distribution == 'Fedora'
  with_items:
  - java-1.8.0-openjdk

- package: state=absent name={{ item }}
  name: Remove package that cause trouble with the regression suite
  with_items:
  - qemu-img
