---
- name: Set default version
  set_fact:
    python_version: ""
    pyxattr_pkg: "pyxattr"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Install jenkins builder standard packages
  package:
    state: present
    name:
    - git # needed for checkout
    - yajl
    - sudo
    - automake
    - autoconf
    - libtool
    - bison
    - dbench # needed for run-tests

- name: Add packages specific to rht builders
  package:
    state: present
    name:
    - python-libcloud
    - python-docopt
  when: '"jenkins_builders_rht" in group_names and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"'

- name: Install jenkins builder Linux packages
  package:
    state: present
    name:
    # used to be pulled by openssl
    - make # needed to run configure
    # needed for some tests
    - net-tools # needed by  ./run-tests.sh
    # used for smoke.sh, for killall
    - psmisc # used for smoke.sh
    - libacl-devel # needed for building gluster
    - nfs-utils # needed for mount.nfs on Linux, needed for regression
    - flex # needed for building gluster
    - perl-Test-Harness # needed to run regression
    - openssl-devel # needed for building gluster
    - lvm2-devel
    - sqlite-devel
    - libxml2-devel # needed for building gluster
    - python{{ python_version }}-devel # needed, but python3
    - userspace-rcu-devel # needed to build gluster
    - libibverbs-devel
    - librdmacm-devel
    - libaio-devel
    - xfsprogs
    # used for testing eventing
    - python{{ python_version }}-requests
    - python{{ python_version }}-flask
    - python{{ python_version }}-prettytable
    # used for build-jobs testing
    - python{{ python_version }}-virtualenv
    #  - python-argparse
    # used for utils/create-files.py
    - "{{ pyxattr_pkg }}"
    # used for regression testing
    - attr
    # used for cli
    - ncurses-devel
    - readline-devel
    # tmpwatch to clean /tmp
    - tmpwatch
    - bc
    # required for https://review.gluster.org/#/c/18532/
    - libcurl-devel
    # required for pstack, used to be pulled by rpm-build
    - gdb
    # required for nfs testing, for 'host'
    - bind-utils
    #required for tmalloc
    - gperftools-devel
    - gperftools-libs
    # required for asan job
    - libasan
    # https://github.com/gluster/glusterfs/pull/3100
    - xxhash-devel
    - xxhash
  when: ansible_system == 'Linux'
# libuuid-devel seems to be missing ?

# remove that package, build georep, see https://github.com/gluster/project-infrastructure/issues/115
- name: Remove packages breaking testsuite
  package:
    state: absent
    name:
    - libtirpc-devel # needed to build ipv6 support
  when: ansible_system == 'Linux' and ansible_distribution_major_version == "7"

- include: pkgs_job_cppcheck.yml
  when: ansible_system == 'Linux'

- include: pkgs_job_rpms.yml
  when: ansible_system == 'Linux'

- include: pkgs_job_lcov.yml
  when: ansible_system == 'Linux'

- include: pkgs_job_shellcheck.yml
  when: '"jenkins_builders_shellcheck" in group_names'

- name: Install jenkins builder Fedora and Centos 8 packages
  package:
    state: present
    name:
    - libtirpc-devel
    - libuuid-devel
    - rpcgen
    - liburing-devel
  when: ansible_system == 'Linux' and ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Install jenkins builder Fedora packages
  package:
    state: present
    name:
# needed for smoke testing on Fedora
# https://bugzilla.redhat.com/show_bug.cgi?id=1623487
    - python3-pylint # not present on Centos 8, so Fedora only
    - python3-flake8 #used for python linting
    - git-clang-format
    - libtsan
  when: ansible_system == 'Linux' and (ansible_distribution == 'Fedora')

- name: Install jenkins builder Centos packages
  package:
    state: present
    name:
    - python-argparse
    # packages for python3 environment
    - python36-devel
    - python36-prettytable
  when: ansible_system == 'Linux' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- package:
    state: present
    name: "{{ item }}"
  name: Install jenkins builder FreeBSD packages
  when: ansible_system == 'FreeBSD'
  with_items:
  - perl5
  - sqlite3
  - pkgconf
  - liburcu
  - gmake
  - bash
# our build script do not seems to work with clang, due to some weird
# argp issue
  - gcc
# adding because it is present on freebsd0.cloud, for parity
  - gsed
  - curl
# requested on https://bugzilla.redhat.com/show_bug.cgi?id=1608707
# debundling
  - e2fsprogs-libuuid
# requested on https://bugzilla.redhat.com/show_bug.cgi?id=1609347
  - argp-standalone
# requested for tmalloc (https://github.com/gluster/project-infrastructure/issues/140)
  - google-perftools
# needed since not installed by default (provides python3 link)
  - python3
  - libxml2
- name: Install python3 on recent FreeBSD
  package:
    state: present
    name:
    - python3
  when: ansible_system == 'FreeBSD' and ansible_distribution_major_version|int > 12
 
- name: Remove package that cause trouble with the regression suite
  package:
    state: absent
    name:
    - qemu-img
    - glusterfs-libs
    - glusterfs
    - glusterfs-api
    - glusterfs-client-xlators
