- name: Create the data file
  modprobe:
    persistent: present
    name: zram
  args:
    creates: /dev/zram0

- name: Format data file to xfs
  filesystem:
    fstype: xfs
    dev: /dev/zram0

- name: Mount /d
  mount:
    path: /d
    src: /dev/zram0
    fstype: xfs
    state: mounted
