---
#
# This playbook is here to make sure that jenkins builder
# on rackspace have one single interface, as the current testsuite
# may fail with more than 1 interface (ideally, this should be fixed
# and bug reports should be opened to track progress)
- name: Clean hosts
  lineinfile:
    state: absent
    dest: /etc/hosts
    regexp: "^(10\\.|2001:)"

- name: Setup hosts file so that IP is in /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_eth0['ipv4']['address'] }} {{ ansible_nodename }}"
    regexp: "^{{ ansible_eth0['ipv4']['address'] }}.*"
  when: location == 'rax'

- name: Make sure firewalld allows traffic from the machine to itself
  firewalld:
    rich_rule: "rule family='ipv4' source address='{{ansible_eth0['ipv4']['address']}}' accept"
    permanent: true
    state: enabled
  when: location == 'rax'

- name: Make sure eth0 is enabled
  lineinfile:
    state: present
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: ^ONBOOT=
    line: ONBOOT=yes

- name: Make sure eth1 is disabled
  lineinfile:
    state: present
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    regexp: ^ONBOOT=
    line: ONBOOT=no
  when: ansible_eth1 is defined
