- set_fact:
    vg_root: "{{ ansible_lvm['lvs']['root']['vg'] }}"

- name: Create the logical volume partition
  lvol:
    vg: "{{ vg_root }}"
    size: 8G
    lv: test

- set_fact:
    vg_root_path: "/dev/mapper/{{ vg_root | replace('-', '--') }}-test"

- name: Setup the filesystem for testing gluster
  filesystem:
    dev: "{{ vg_root_path }}"
    fstype: xfs

- name: Mount the device for testing gluster
  mount:
    name: /d
    fstype: xfs
    src: "{{ vg_root_path }}"
    state: mounted
