- name: Create the data file
  modprobe:
    # not supported on the version of ansible we use for now
    # https://github.com/ansible-collections/community.general/commit/29f5033737a7fd86349ff3daab7d7ee7db66ad00
    #    persistent: present
    name: zram

- name: Format data file to xfs
  filesystem:
    fstype: xfs
    dev: /dev/zram0

- name: Mount /d
  mount:
    path: /d
    src: /dev/zram0
    fstype: xfs
    state: mounted
