---
- name: Disable lvm archive
  lvm_config:
    name: archive 
    section: backup 
    value: '0'

- name: Raise memory limit for activation
  lvm_config:
    name: reserved_memory
    section: activation
    value: '32768'
  when: ansible_distribution_major_version|int < 34 and ansible_distribution_major_version|int != 8
