---
- package:
    name:
    - python3-botocore
    - python3-boto3
    state: installed

- ini_file:
    path: /etc/boto.cfg
    section: Credentials
    option: aws_access_key_id
    value: "{{ aws_access_key }}"
  no_log: True

- ini_file:
    path: /etc/boto.cfg
    section: Credentials
    option: aws_secret_access_key
    value: "{{ aws_secret_key }}"
  no_log: True

#enable when EC2 support ecdsa one day...
#- ec2_key:
#    name: bastion_keypair
#    key_material: "{{ lookup('file', '/home/ansible_admin/.ssh/id_ecdsa.pub') }}"
#  environment:
#    https_proxy: http://squid.int.rht.gluster.org:3128/
  
