---
- name: "Create the initial VPC"
  amazon.aws.ec2_vpc_net:
    name: "Production VPC"
    # this is the 1st unallocated block from the previous VPC
    cidr_block: "172.30.0.0/16"
    ipv6_cidr: true
  register: vpc_res

- set_fact:
    ipv6_range: "{{ vpc_res.vpc.ipv6_cidr_block_association_set[0].ipv6_cidr_block | ansible.utils.ipsubnet('64','1')  }}"
    vpc_id: "{{ vpc_res.vpc.id }}"

- name: Create the gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"

# it need to be created after the gateway, so the route is configured by default
- name: Create the subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "172.30.1.0/24"
    assign_instances_ipv6: true
    ipv6_cidr: "{{ ipv6_range }}"
  register: subnet_res

- set_fact:
    subnet_id: "{{ subnet_res.subnet.id }}"

- name: Create security group for builders
  amazon.aws.ec2_group:
    name: ansible-gluster-builders-sg
    description: Ansible managed security group for builders
    vpc_id: "{{ vpc_id }}"
    rules:
    - proto: tcp
      ports:
      - 22
      cidr_ip: 8.43.85.181/32
      rule_desc: allow nagios/ant-queen/etc on port 22
    - proto: tcp
      ports:
      - 22
      cidr_ip: 172.31.32.0/20
      rule_desc: allow the internal servers on port 22
    - proto: tcp
      ports:
      - 22
      cidr_ip: 8.43.85.184/32
      rule_desc: allow jenkins on port 22
    - proto: icmp
      cidr_ip: 0.0.0.0/0
      rule_desc: allow icmp echo for icmp
      from_port: 8
      to_port: -1
    - proto: tcp
      ports:
      - 5666
      - 4949
      cidr_ip: 8.43.85.181/32
      rule_desc: allow nrpe/munin from the cage

- name: Create security group for softserve
  amazon.aws.ec2_group:
    name: ansible-gluster-softserve-sg
    description: Ansible managed security group for softserve builders
    vpc_id: "{{ vpc_id }}"
    rules:
    - proto: tcp
      ports:
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all on port 22
    - proto: icmp
      cidr_ip: 0.0.0.0/0
      rule_desc: allow icmp echo for icmp
      from_port: 8
      to_port: -1
