---
- name: "Create the initial VPC"
  amazon.aws.ec2_vpc_net:
    name: "Production VPC"
    # this is the 1st unallocated block from the previous VPC
    cidr_block: "172.30.0.0/16"
    ipv6_cidr: true
  register: vpc_res

- amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_res.vpc.id }}"
    cidr: "172.30.1.0/24"
    assign_instances_ipv6: true
    ipv6_cidr: "{{ vpc_res.ipv6_cidr_block_association_set[0].ipv6_cidr_block }}"
  register: subnet_res
  
- debug:
    var: subnet_res
