---
- name: "Create the initial VPC"
  amazon.aws.ec2_vpc_net:
    name: "Production VPC"
    # this is the 1st unallocated block from the previous VPC
    cidr_block: "172.30.0.0/16"
    ipv6_cidr: true
  register: vpc_res

- set_fact:
    ipv6_range: "{{ vpc_res.vpc.ipv6_cidr_block_association_set[0].ipv6_cidr_block | ansible.utils.ipsubnet('64','1')  }}"
    vpc_id: "{{ vpc_res.vpc.id }}"

- amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "172.30.1.0/24"
    assign_instances_ipv6: true
    ipv6_cidr: "{{ ipv6_range }}"
  register: subnet_res

- set_fact:
    subnet_id: "{{ subnet_res.subnet.id }}"

- name: Create the gateway
  amazon.aws.ec2_vpc_igw:
    name: "Production gateway"
    vpc_id: "{{ vpc_id }}"
