---
# TODO add a way to retrieve it
- set_fact:
    instance: "i-002ac77efbcca7cc8"
# ideally, none of this should be hardcoded

- name: Associate the log server with the public IP
  ec2_eip:
    region: "{{ aws_region }}"
    device_id: "{{ instance }}"
    ip: 18.219.45.211

- name: Associate the public IP with the DNS
  route53:
    state: present
    record: logs.aws.gluster.org
    zone: aws.gluster.org
    type: A
    ttl: 7200
    value: 18.219.45.211
    wait: yes

- name: Create the security group for the 
  ec2_group:
    name: ansible-gluster-openvpn-sg
    description: Ansible managed security group for openvpn/logs nodes
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
    - proto: tcp
      ports:
      - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for ssh
    - proto: tcp
      ports:
      - 1194
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for openvpn
    - proto: tcp
      ports:
      - 80
      - 443
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for web
    - proto: icmp
      cidr_ip: 0.0.0.0/0
      rule_desc: allow all for icmp

- name: Add a block device 
  ec2_vol:
    name: "logs_aws_storage"
    instance: "{{ instance }}"
    region: "{{ aws_region }}"
    volume_size: "6"
    #this parameter is ignored, it go on nvme1n1
    device_name: sdd

- name: Create the datadisk
  filesystem:
    fstype: xfs
    dev: /dev/nvme1n1
  delegate_to: logs.aws.gluster.org

- name: Mount the new FS
  mount: 
    name: /var/www/glusterfs-logs
    src: /dev/nvme1n1
    fstype: "xfs"
    state: mounted
  delegate_to: logs.aws.gluster.org
  
