---
- amazon.aws.iam_user:
    name: "{{ item }}"
    state: present
  loop:
  - softserve
  - misc
  - deepshikha
  - sahina
  - rakshitha
  - akraitma

- community.aws.iam_group:
    name: Developers
    state: present
    users:
    - sahina

- community.aws.iam_group:
    name: softserve
    state: present
    users:
    - softserve
    managed_policy:
    - arn:aws:iam::aws:policy/AmazonEC2FullAccess
    purge_policy: True
    purge_users: True

- community.aws.iam_group:
    name: gluster-janitors 
    state: present
    users:
    - misc
    - deepshikha
    - rakshitha
    managed_policy:
    - arn:aws:iam::aws:policy/AdministratorAccess
    purge_policy: True
    purge_users: True

- community.aws.iam_group:
    name: downstream-readonly
    state: present
    users:
    - akraitma
    managed_policy:
    - arn:aws:iam::aws:policy/ReadOnlyAccess
    purge_policy: True
    purge_users: True

