---
- name: See if we are the master
  set_fact:
    is_master: "{{ ansible_hostname == master }}"

# seems variable defined in a role are not visible in hostvers, while
# set_fact is
- name:
  set_fact:
    vip_copy: "{{ vip }}"

- name: Generate a random password
  set_fact:
    password: "{{ lookup('password', '~/keepalived_pass' + master + 'length=6') }}"

- name: Install keepalived
  package:
    name: keepalived
    state: installed

- name: Deploy configuration
  template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.conf
  notify: Restart keepalived

- name: Deploy the script to notify changes
  template:
    dest: /usr/libexec/keepalived/notify_script.sh
    src: notify_script.sh
    mode: 0755

- include_tasks: firewalld.yml
  when: use_firewalld|bool

- name: Start service
  service:
    name: keepalived
    enabled: True
    state: started

- name: Make sure services can start and listen to the floating ips
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
