---
- name: postalias internal
  command: postalias internal.aliases
  args:
    chdir: /etc/postfix
 
- name: postalias mailman
  command: postalias mailman.aliases
  args:
    chdir: /etc/postfix

- name: postalias external
  command: postalias external.aliases
  args:
    chdir: /etc/postfix

- name: postalias virtual
  command: postmap virtual.aliases
  args:
    chdir: /etc/postfix

- name: postmap client_a_access
  command: postmap client_a_access
  args:
    chdir: /etc/postfix
