---
- name: Install required packages
  package:
    state: present
    name: "{{ item }}"
  with_items:
  - python-virtualenv
  - gcc
  - git

# TODO create the directory /fstat, do the git checkout
# automate update
# set configuration file, and database creation
# and selinux boolean
- name: Add tmpfiles snippet
  template:
    dest: /etc/tmpfiles.d/fstat.conf
    src: fstat.tmpfiles.conf
  notify: Create fstat systemd tmpfile

- name: Add gunicorn systemd service
  template:
    dest: /etc/systemd/system/fstat.service
    src: fstat.service
  notify: Reload systemd

- meta: flush_handlers

- name: Start the fstat service
  service:
    name: fstat
    enabled: True
    state: started
- name: Configure Cron tab centos
  cron:
    name: fstat centos
    minute: "0"
    hour: "1"
    job: "/fstat/env/bin/python /fstat/code/manage.py process_jobs -n 3 -j centos6-regression"

- name: Configure Cron tab for netbsd
  cron:
    name: fstat netbsd
    minute: "0"
    hour: "1"
    job: "/fstat/env/bin/python /fstat/code/manage.py process_jobs -n 3 -j netbsd7-regression"

- name: Configure Cron tab for regression-test-burn-in
  cron:
    name: fstat regression-test-burn-in
    minute: "0"
    hour: "1"
    job: "/fstat/env/bin/python /fstat/code/manage.py process_jobs -n 3 -j regression-test-burn-in"

- name: Configure Cron tab for regression-with-multiplex
  cron:
    name: fstat regression-with-multiplex
    minute: "0"
    hour: "1"
    job: "/fstat/env/bin/python /fstat/code/manage.py process_jobs -n 3 -j regression-with-multiplex"
