---
- name: Install required packages
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - python-virtualenv
    - gcc
    - git

# TODO create the directory /fstat, do the git checkout
# automate update
# set configuration file, and database creation
# and selinux boolean
- name: Add tmpfiles snippet
  template:
    dest: /etc/tmpfiles.d/fstat.conf
    src: fstat.tmpfiles.conf
  notify: Create fstat systemd tmpfile

- name: Add gunicorn systemd service
  template:
    dest: /etc/systemd/system/fstat.service
    src: fstat.service
  notify: Reload systemd

- meta: flush_handlers

- name: Start the fstat service
  service:
    name: fstat
    enabled: true
    state: started

- name: Configure Crontab
  cron:
    name: fstat {{item.name}}
    minute: "0"
    hour: "1"
    job: "SENTRY_DSN=\"{{fstat_config['sentry_dsn']}}\" /fstat/env/bin/python /fstat/code/manage.py process_jobs -n 3 -j {{item.job}}"
  with_items:
    - {name: 'centos', job: 'centos7-regression'}
    - {name: 'regression-test-burn-in', job: 'regression-test-burn-in'}
    - {name: 'regression-test-with-multiplex', job: 'regression-test-with-multiplex'}
    - {name: 'line-coverage', job: 'line-coverage'}
