---
- user:
    name: "{{user}}"

- name: Install required packages
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - python-virtualenv
    - gcc
    - git

# TODO set configuration file, and database creation
# and selinux boolean

- name: create fstat directory
  file:
    path: /fstat/code state=directory

- name: Check if virtualenv exists
  local_action: stat path=/fstat/venv
  register: venv

- name: create virtualenv if it does not exists
  command: virtualenv /fstat/venv
  when: not venv.stat.exists

- name: clone or update fstat repo
  git:
    repo: https://github.com/gluster/fstat
    dest: /fstat/code

- name: install dependencies
  pip:
    requirements=/fstat/code/requirements.txt
    virtualenv=/fstat/venv

- name: Add tmpfiles snippet
  template:
    dest: /etc/tmpfiles.d/fstat.conf
    src: fstat.tmpfiles.conf
  notify: Create fstat systemd tmpfile

- name: Add gunicorn systemd service
  template:
    dest: /etc/systemd/system/fstat.service
    src: fstat.service
  notify: Reload systemd

- meta: flush_handlers

- name: Start the fstat service
  service:
    name: fstat
    enabled: True
    state: started

- name: Configure Crontab
  cron:
    name: fstat {{item.name}}
    minute: "0"
    hour: "1"
    job: "/fstat/venv/bin/python /fstat/code/manage.py process_jobs -n 3 -j {{item.job}}"
  with_items:
    - { name: 'centos', job: 'centos6-regression' }
    - { name: 'netbsd', job: 'netbsd7-regression' }
    - { name: 'regression-test-burn-in', job: 'regression-test-burn-in' }
    - { name: 'regression-test-with-multiplex', job: 'regression-test-with-multiplex' }
