- hosts: all:!cage_externally_facing
  roles:
  - openssh

- hosts: cage_externally_facing
  roles:
  - role: openssh
    filters: "{{ ssh_ciphers_filter }}"
    when: ansible_fqdn != 'gerrit-new.rht.gluster.org'

- hosts: all
  roles:
  - base
  - role: selinux
    when: ansible_system == 'Linux' and ansible_distribution != 'Debian'
  - role: ntp
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8
  - role: chrony
    servers: "{{ ntp_servers }}"
    when: ansible_system == 'Linux' and ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8
  - role: shell_timeout
    when: ansible_system == 'Linux'
  - unattended_updates
  - ssh_keys_bastion
