---
- hosts: firewall_rht
  vars:
    outgoing_ip: 8.43.85.181
    use_firewalld: False
  roles:
  - role: network_conf_ifcfg
    interface: "{{ common_interface }}"
    ip: "{{ common_ip }}/24"
  - role: network_conf_ifcfg
    interface: "{{ interco_fw_interface }}"
    ip: "{{ interco_fw_ip }}/24"
  - role: keepalived_fw
    master: masa
    group: firewall_rht
    vip:
      public:
        interface: "{{ public_interface }}"
        address: 8.43.85.181
        prefix: 24
      public6:
        interface: "{{ public_interface }}"
        address: "2620:52:3:1:2023::3"
        prefix: 128 
      common:
        interface: "{{ common_interface }}"
        address: 172.24.1.181
        prefix: 24
  - role: conntrackd
    sync_interface: "{{ interco_fw_interface }}"
    group: firewall_rht
  - role: nftables
  - role: rsyslog
