---
- hosts: haplometrosis.rht.gluster.org
  vars:
    # default value for builders
    distribution: Centos
    version: 7
  roles:
  - role: guest_jenkins_builder_int_rht
    number: 1
  - role: guest_jenkins_builder_int_rht
    number: 2
 
- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: rht_builder_deb10
    lan_ip: 91
    hostname: builder-deb10-1
  - role: rht_builder_ubuntu2004
    lan_ip: 94
    hostname: builder-ubuntu2004-1


- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: rht_builder_f32
    lan_ip: 92
    hostname: builder-f32-1

- hosts: pleometrosis.rht.gluster.org
  roles:
  - role: rht_builder_f32
    lan_ip: 93
    hostname: builder-f32-2


- hosts: jenkins_builders_rht
  tasks:
  - name: Resize the disk of the builders
    lvol:
      vg: "vg_root_{{ ansible_fqdn }}"
      lv: root
      size: 18G
    when: ansible_system == 'Linux'
  - name: Make sure the filesystem is resized
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/vg_root_{{ ansible_fqdn | replace('-', '--') }}-root"
      resizefs: True
    when: ansible_system == 'Linux'


