- hosts: aws_provisioner
  roles:
  - role: aws-s3_bucket_backup
    prefix: gluster.org
    project: download-backups
  

- hosts: download
  tasks:
  - package:
        state: present
        name: createrepo
  roles:
  - role: httpd_download
    website_domain: download.gluster.org
    document_root: /var/www/html
  - role: logrotate_compress
  - role: download_users

