---
- hosts: proxy
  roles:
  - role: keepalived
    master: proxy01.rht.gluster.org
    group: proxy
    vip:
      public:
        interface: eth0
        address: 8.43.85.185
        prefix: 24

  - role: network_conf_ifcfg
    interface: eth1
    ip: "{{ internal_ip }}/24"
    # since firewalld modify the file, we need to not revert the change 
    when: ansible_eth1.ipv4.address != internal_ip

  - role: cert_syncer
    group: proxy
    interface: eth1

  - role: proxy_service_ordering

  - role: nginx_proxy_vhost
    domain: bits.gluster.org
    backends:
    - bits.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: ci-logs.gluster.org
    backends:
    - http.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: fstat.gluster.org
    backends:
    - fstat.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: failurestat.gluster.org
    backends:
    - fstat.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: softserve.gluster.org
    backends:
    - softserve.int.rht.gluster.org

#  - role: nginx_proxy_vhost
#    domain: fstat.test.gluster.org
#    backends:
#    - fstat.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: planet.gluster.org
    backends:
    - planet.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: nagios.gluster.org
    backends:
    - nagios.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: munin.gluster.org
    backends:
    - munin.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: bugs.gluster.org
    backends:
    - bugs.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: download.gluster.org
    backends:
    - download.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: sentry.gluster.org
    backends:
    - sentry.int.rht.gluster.org:9000

  - role: nginx_proxy_vhost
    domain: lists.gluster.org
    custom_config: | 
      if ($http_user_agent ~* "axios/") {
        return 500;
      }
    backends:
    - lists-el7.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: hooks.gluster.org
    backends:
    - ghwebhooks.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: community.gluster.org
    backends:
    - redirector.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: gluster.org
    backends:
    - redirector.int.rht.gluster.org

  - role: nginx_proxy_vhost
    domain: supercolony.gluster.org
    backends:
    - redirector.int.rht.gluster.org

