---
- hosts: lists
  vars:
    # the variable is used for postfix_gluster and mailman
    mailing_lists:
    - gluster-devel
    - gluster-users
    - advisors
    - gluster-infra
    - bugs
    - mailman
    - test
    - board
    - announce
    - cinder.glusterfs.ci
    - maintainers
    - packaging
    - social-media
    - heketi-devel
    - integration
    - automated-testing
    - tlc
    - ci-results
  roles:
  - postgrey
  # temporary role
  - role: mailman_gluster
    website_domain: lists.gluster.org
    mail_domain: gluster.org
#    dnsbl_mailman:
# too much false positive
#    - b.barracudacentral.org
#    - cbl.abuseat.org
#    - dnsbl.dronebl.org

  - role: postfix_gluster
    blacklists:
    - b.barracudacentral.org
# too much false positive
#    - dnsbl-3.uceprotect.net
    - dnsbl-2.uceprotect.net
    # see private repo for the vars, on hostvars/supercolony
    # since emails are private
    email_aliases: "{{ mail_aliases }}"
    devnull_domains:
    - review.gluster.org
    - build.gluster.org
    mail_domain: gluster.org
    blocked_ip_range:
    - 188.72.187.0/24
